[package]
name = "ecc-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ecc-frontend"
path = "src/main.rs"

[dependencies]
regex = "1"
snailquote = "0.3.0"
quote = "1.0"
trinity = { git = "https://github.com/were/trinity", branch = "master" }

