[features]
x86 = []

[package]
name = "ecc-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ecc"
path = "src/main.rs"

[dependencies]
regex = "1"
snailquote = "0.3.0"
quote = "1.0"
trinity = { path = "./trinity" }

